apiVersion: v1
kind: ConfigMap
metadata:
  name: route-list
data:
  route-list.json: |
    {
      "route-keys": [
        "service-a",
        "service-b",
        "service-c"
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: randomise-route-list
  labels:
    app: randomise-route-list
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: randomise-route-list
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomise-route-list
spec:
  selector:
    matchLabels:
      app: randomise-route-list
  replicas: 1
  template:
    metadata:
      labels:
        app: randomise-route-list
    spec:
      containers:
        - name: randomise-route-list
          image: australia-southeast1-docker.pkg.dev/solo-test-236622/apac/randomise-route-keys:v0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--port"
            - "9080"
          ports:
            - containerPort: 9080
          env:
            - name: LOG_LEVEL
              value: debug
            - name: ROUTE_LIST_FILE_PATH
              value: /etc/config/route-list.json
          volumeMounts:
            - mountPath: /etc/config
              name: route-list-config
      volumes:
        - name: route-list-config
          configMap:
            name: route-list