name: Regression Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches: '**'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: checkout-code
        uses: actions/checkout@v3

      - name: execute-test
        shell: bash
        run: make test